# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

INNC <- function(dlist, n, d) {
    .Call(`_INN_INNC`, dlist, n, d)
}

INNS <- function(dlist, n, d) {
    .Call(`_INN_INNS`, dlist, n, d)
}

INNCtest <- function(dlist, n, d, REP) {
    .Call(`_INN_INNCtest`, dlist, n, d, REP)
}

INNStest <- function(dlist, n, d, REP) {
    .Call(`_INN_INNStest`, dlist, n, d, REP)
}

INN2 <- function(dlist, dlistm, n, d) {
    .Call(`_INN_INN2`, dlist, dlistm, n, d)
}

INN2test <- function(dlist, n, d, REP) {
    .Call(`_INN_INN2test`, dlist, n, d, REP)
}

